/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as PerfilRouteImport } from './routes/perfil'
import { Route as MeusCursosRouteImport } from './routes/meus-cursos'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AssinaturasRouteImport } from './routes/assinaturas'
import { Route as AfiliacaoRouteImport } from './routes/afiliacao'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CursoIdRouteImport } from './routes/curso.$id'
import { Route as CheckoutIdRouteImport } from './routes/checkout.$id'
import { Route as CursoIdIndexRouteImport } from './routes/curso.$id.index'
import { Route as AdminCursoIdRouteImport } from './routes/admin.curso.$id'
import { Route as CursoIdModuloModuleIdRouteImport } from './routes/curso.$id.modulo.$moduleId'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const PerfilRoute = PerfilRouteImport.update({
  id: '/perfil',
  path: '/perfil',
  getParentRoute: () => rootRouteImport,
} as any)
const MeusCursosRoute = MeusCursosRouteImport.update({
  id: '/meus-cursos',
  path: '/meus-cursos',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AssinaturasRoute = AssinaturasRouteImport.update({
  id: '/assinaturas',
  path: '/assinaturas',
  getParentRoute: () => rootRouteImport,
} as any)
const AfiliacaoRoute = AfiliacaoRouteImport.update({
  id: '/afiliacao',
  path: '/afiliacao',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CursoIdRoute = CursoIdRouteImport.update({
  id: '/curso/$id',
  path: '/curso/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutIdRoute = CheckoutIdRouteImport.update({
  id: '/checkout/$id',
  path: '/checkout/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const CursoIdIndexRoute = CursoIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => CursoIdRoute,
} as any)
const AdminCursoIdRoute = AdminCursoIdRouteImport.update({
  id: '/curso/$id',
  path: '/curso/$id',
  getParentRoute: () => AdminRoute,
} as any)
const CursoIdModuloModuleIdRoute = CursoIdModuloModuleIdRouteImport.update({
  id: '/modulo/$moduleId',
  path: '/modulo/$moduleId',
  getParentRoute: () => CursoIdRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/afiliacao': typeof AfiliacaoRoute
  '/assinaturas': typeof AssinaturasRoute
  '/login': typeof LoginRoute
  '/meus-cursos': typeof MeusCursosRoute
  '/perfil': typeof PerfilRoute
  '/signup': typeof SignupRoute
  '/checkout/$id': typeof CheckoutIdRoute
  '/curso/$id': typeof CursoIdRouteWithChildren
  '/admin/curso/$id': typeof AdminCursoIdRoute
  '/curso/$id/': typeof CursoIdIndexRoute
  '/curso/$id/modulo/$moduleId': typeof CursoIdModuloModuleIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/afiliacao': typeof AfiliacaoRoute
  '/assinaturas': typeof AssinaturasRoute
  '/login': typeof LoginRoute
  '/meus-cursos': typeof MeusCursosRoute
  '/perfil': typeof PerfilRoute
  '/signup': typeof SignupRoute
  '/checkout/$id': typeof CheckoutIdRoute
  '/admin/curso/$id': typeof AdminCursoIdRoute
  '/curso/$id': typeof CursoIdIndexRoute
  '/curso/$id/modulo/$moduleId': typeof CursoIdModuloModuleIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/afiliacao': typeof AfiliacaoRoute
  '/assinaturas': typeof AssinaturasRoute
  '/login': typeof LoginRoute
  '/meus-cursos': typeof MeusCursosRoute
  '/perfil': typeof PerfilRoute
  '/signup': typeof SignupRoute
  '/checkout/$id': typeof CheckoutIdRoute
  '/curso/$id': typeof CursoIdRouteWithChildren
  '/admin/curso/$id': typeof AdminCursoIdRoute
  '/curso/$id/': typeof CursoIdIndexRoute
  '/curso/$id/modulo/$moduleId': typeof CursoIdModuloModuleIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/afiliacao'
    | '/assinaturas'
    | '/login'
    | '/meus-cursos'
    | '/perfil'
    | '/signup'
    | '/checkout/$id'
    | '/curso/$id'
    | '/admin/curso/$id'
    | '/curso/$id/'
    | '/curso/$id/modulo/$moduleId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/afiliacao'
    | '/assinaturas'
    | '/login'
    | '/meus-cursos'
    | '/perfil'
    | '/signup'
    | '/checkout/$id'
    | '/admin/curso/$id'
    | '/curso/$id'
    | '/curso/$id/modulo/$moduleId'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/afiliacao'
    | '/assinaturas'
    | '/login'
    | '/meus-cursos'
    | '/perfil'
    | '/signup'
    | '/checkout/$id'
    | '/curso/$id'
    | '/admin/curso/$id'
    | '/curso/$id/'
    | '/curso/$id/modulo/$moduleId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  AfiliacaoRoute: typeof AfiliacaoRoute
  AssinaturasRoute: typeof AssinaturasRoute
  LoginRoute: typeof LoginRoute
  MeusCursosRoute: typeof MeusCursosRoute
  PerfilRoute: typeof PerfilRoute
  SignupRoute: typeof SignupRoute
  CheckoutIdRoute: typeof CheckoutIdRoute
  CursoIdRoute: typeof CursoIdRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/perfil': {
      id: '/perfil'
      path: '/perfil'
      fullPath: '/perfil'
      preLoaderRoute: typeof PerfilRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/meus-cursos': {
      id: '/meus-cursos'
      path: '/meus-cursos'
      fullPath: '/meus-cursos'
      preLoaderRoute: typeof MeusCursosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/assinaturas': {
      id: '/assinaturas'
      path: '/assinaturas'
      fullPath: '/assinaturas'
      preLoaderRoute: typeof AssinaturasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/afiliacao': {
      id: '/afiliacao'
      path: '/afiliacao'
      fullPath: '/afiliacao'
      preLoaderRoute: typeof AfiliacaoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/curso/$id': {
      id: '/curso/$id'
      path: '/curso/$id'
      fullPath: '/curso/$id'
      preLoaderRoute: typeof CursoIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout/$id': {
      id: '/checkout/$id'
      path: '/checkout/$id'
      fullPath: '/checkout/$id'
      preLoaderRoute: typeof CheckoutIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/curso/$id/': {
      id: '/curso/$id/'
      path: '/'
      fullPath: '/curso/$id/'
      preLoaderRoute: typeof CursoIdIndexRouteImport
      parentRoute: typeof CursoIdRoute
    }
    '/admin/curso/$id': {
      id: '/admin/curso/$id'
      path: '/curso/$id'
      fullPath: '/admin/curso/$id'
      preLoaderRoute: typeof AdminCursoIdRouteImport
      parentRoute: typeof AdminRoute
    }
    '/curso/$id/modulo/$moduleId': {
      id: '/curso/$id/modulo/$moduleId'
      path: '/modulo/$moduleId'
      fullPath: '/curso/$id/modulo/$moduleId'
      preLoaderRoute: typeof CursoIdModuloModuleIdRouteImport
      parentRoute: typeof CursoIdRoute
    }
  }
}

interface AdminRouteChildren {
  AdminCursoIdRoute: typeof AdminCursoIdRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminCursoIdRoute: AdminCursoIdRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface CursoIdRouteChildren {
  CursoIdIndexRoute: typeof CursoIdIndexRoute
  CursoIdModuloModuleIdRoute: typeof CursoIdModuloModuleIdRoute
}

const CursoIdRouteChildren: CursoIdRouteChildren = {
  CursoIdIndexRoute: CursoIdIndexRoute,
  CursoIdModuloModuleIdRoute: CursoIdModuloModuleIdRoute,
}

const CursoIdRouteWithChildren =
  CursoIdRoute._addFileChildren(CursoIdRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  AfiliacaoRoute: AfiliacaoRoute,
  AssinaturasRoute: AssinaturasRoute,
  LoginRoute: LoginRoute,
  MeusCursosRoute: MeusCursosRoute,
  PerfilRoute: PerfilRoute,
  SignupRoute: SignupRoute,
  CheckoutIdRoute: CheckoutIdRoute,
  CursoIdRoute: CursoIdRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
